name: wazzup gof diploma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Build Docker image
        run: docker build -t diploma-tests .

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -e API_BASE_URL=${{ secrets.API_BASE_URL }} \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            -e API_TOKEN=${{ secrets.API_TOKEN }} \
            -e TEST_USER_EMAIL=${{ secrets.TEST_USER_EMAIL }} \
            -e TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }} \
            -e TEST_CHANNEL_TOKEN=${{ secrets.TEST_CHANNEL_TOKEN }} \
            -e TEST_CHANNEL_TOKEN_2=${{ secrets.TEST_CHANNEL_TOKEN_2 }} \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            diploma-tests

      - name: Generate Allure report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            --entrypoint npx \
            diploma-tests allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v7.0.1
        if: always()
        with:
          name: allure-report
          path: allure-report/
